--local _G = GLOBAL
local other_prefabs = {
    mastupgrade_lightningrod_top = true, forge_abigail_flower = true, cave_banana_tree = true, wardrobe_blueprint = true, bibingka = true, halloweencandy_7 = true, oceanfishingbobber_crow = true, winter_ornament_light2 = true, pepperpopper_spice_sugar = true, honeyham_spice_chili = true, glowberrymousse_spice_salt = true, wintersfeastfuel = true, quagmire_foliage_cooked = true, boatpatch = true, wall_stone_item_blueprint = true, stalagmite = true, baconeggs_spice_garlic = true, quagmire_goatmum = true, icepack_blueprint = true, spear_lance = true, quagmire_seedpacket_7 = true, oceanfishinglure_hermit_heavy = true, drumstick_cooked = true, gunpowder = true, oceanfishingbobber_robin_winter_tacklesketch = true, dragontailhat = true, wetgoop_spice_chili = true, meatysalad_spice_garlic = true, quagmire_rubble_clocktower = true, sandspike_med = true, shroom_skin = true, brush = true, pig_token = true, waveyjones = true, quagmire_food_056 = true, barnaclepita_spice_sugar = true, halloweenpotion_bravery_small = true, stinger = true, chesspiece_pipe_moonglass = true, chesspiece_anchor_sketch = true, rock_avocado_fruit = true, honeyham_spice_garlic = true, quagmire_food_029 = true, portablecookpot = true, van_snaptooth = true, ice = true, fireballstaff = true, moon_tree_short = true, atrium_key = true, bishop = true,
    molehat = true, cave_banana = true, lobsterdinner = true, pithpike = true, cave_exit = true, kabobs = true, warg = true, blowdart_yellow_blueprint = true, cave_banana_stump = true, quagmire_food_038 = true, firehound = true, bat = true, wall_moonrock_item_blueprint = true, scorched_skeleton = true, leif_sparse = true, slurtlehat = true, quagmire_seedpacket_1 = true, turf_woodfloor_blueprint = true, oceanfishingbobber_crow_floater = true, berrybush = true, van_lureplant = true, batbat_blueprint = true, seafaring_prototyper_blueprint = true, lavaarena_healingflowerhat = true, lightbulb = true, trinket_29 = true, candybag_blueprint = true, boat_item_blueprint = true, forge_woodarmor = true, eel_cooked = true, pickaxe = true, chesspiece_carrat = true, lavae_egg_cracked = true, powcake = true, wortox = true, telebase = true, battlestandard_speed = true, shark = true, slingshot = true, baconeggs = true, salsa = true, fishsticks_spice_chili = true, lobsterbisque_spice_garlic = true, armormarble_blueprint = true, lavaarena_armormediumdamager = true, californiaroll_spice_sugar = true, quagmire_rubble_cathedral = true, quagmire_food_009 = true, quagmire_food_008 = true, critter_dragonling = true,
    rock_petrified_tree_med = true, tentaclespots = true, panflute_blueprint = true, trident_blueprint = true, quagmire_food_061 = true, chesspiece_klaus_sketch = true, woodie = true, construction_container = true, oceanfishinglure_hermit_drowsy_tacklesketch = true, stalagmite_tall_med = true, yellowamulet = true, lavaarena_healinggarlandhat = true, honeyham_spice_sugar = true, firesuppressor = true, chester = true, spat = true, lavaarena_armor_hprecharger = true, turf_rocky = true, beeguard = true, evergreen_tall = true, bedroll_furry = true, chesspiece_toadstool_marble = true, bugnet_blueprint = true, jellybean = true, minisign_item_blueprint = true, hermit_pearl = true, chesspiece_knight_marble = true, lutefisk = true, pighead = true, icehound = true, carrat_planted = true, featherfan_blueprint = true, portablecookpot_item = true, moonglass_wobster_den = true, potatotornado_spice_sugar = true, batcave = true, boat = true, grass_umbrella = true, marbletree = true, van_birchnutdrake = true, bullkelp_plant = true, barnaclesushi_spice_garlic = true, lucky_goldnugget = true, spiderden = true, fossilspike = true, chesspiece_klaus_moonglass = true, slingshotammo_gold = true, quagmire_goatkid = true, chesspiece_claywarg_marble = true, fence = true,
    leafymeatburger_spice_sugar = true, hotchili = true, waffles_spice_chili = true, winter_ornament_plain2 = true, winch = true, opalpreciousgem = true, stuffing = true, quagmire_parkspike = true, oceanfishingrod_blueprint = true, trinket_41 = true, skeleton_player = true, trinket_14 = true, slingshotammo_marble = true, oceanfishingbobber_goose_tacklesketch = true, asparagus_seeds = true, oceanfish_small_5 = true, barnaclestuffedfishhead_spice_garlic = true, carrat_ghostracer = true, taffy_spice_salt = true, petals = true, balloons_empty = true, forge_slingshot = true, townportal_blueprint = true, taffy_spice_garlic = true, sculpture_knight = true, quagmire_rubble_clock = true, beefalo = true, researchlab3_blueprint = true, turf_forest = true, moqueca_spice_garlic = true, bushhat_blueprint = true, trailmix_spice_chili = true, van_bishop = true, rock_avocado_fruit_ripe_cooked = true, year_of_the_pig_event_frontend = true, quagmire_food_045 = true, hermitcrab = true, bundlewrap_blueprint = true, snurtle = true, quagmire_park_urn = true, hambat_blueprint = true, stuffedeggplant_spice_sugar = true, californiaroll_spice_salt = true, knight_nightmare = true, halloween_ornament_3 = true, barnaclesushi_spice_chili = true, shadowminer = true, toadstool_cap = true, crawlingnightmare = true, marblebean_blueprint = true,
    green_cap_cooked = true, spider_moon = true, flowersalad_spice_chili = true, chesspiece_carrat_stone = true, willow = true, slurtle = true, multiplayer_portal_moonrock = true, quagmire_food_016 = true, bonesoup_spice_garlic = true, waterplant_baby = true, jammypreserves_spice_garlic = true, fast_farmplot_blueprint = true, orangestaff = true, potato_cooked = true, van_bishop_emp = true, blowdart_fire_blueprint = true, marsh_plant = true, steeringwheel_item = true, trinket_22 = true, eggplant_seeds = true, quagmire_food_025 = true, mandrakesoup = true, californiaroll_spice_chili = true, tophat_blueprint = true, spiderhat = true, burntstick = true, trunkvest_summer = true, rock_flintless_low = true, purplegem_blueprint = true, boatlip = true, quagmire_seeds_7 = true, winter_food2 = true, pumpkin_lantern_blueprint = true, wall_hay_item_blueprint = true, insanityrock = true, pumpkincookie_spice_sugar = true, brush_blueprint = true, leafymeatsouffle = true, shadowchanneler = true, hallowed_nights_event_backend = true, deer_antler2 = true, rock_avocado_fruit_sprout_sapling = true, butterflymuffin_spice_chili = true, quagmire_park_fountain = true, yotc_carrat_race_start = true, tentacle_pillar_arm = true, flower_cave_triple = true, chesspiece_clayhound = true, pillar_cave = true, chesspiece_rook_sketch = true,
    walkingplank = true, transistor_blueprint = true, oceanfish_medium_2 = true, chesspiece_anchor = true, ancient_altar = true, splash_lavafx = true, sculpture_rook = true, quagmire_crabtrap = true, quagmire_food_057 = true, multitool_axe_pickaxe = true, antliontrinket = true, barnaclestuffedfishhead = true, van_spider_warrior = true, raincoat_blueprint = true, nightmare_timepiece = true, succulent_picked = true, oceanfishinglure_spinner_blue = true, trinket_8 = true, quagmire_coin1 = true, meatysalad_spice_sugar = true, winter_ornament_boss_fuelweaver = true, ruinsrelic_chipbowl = true, pond = true, turf_carpetfloor = true, book_elemental = true, quagmire_food_053 = true, hotchili_spice_salt = true, science_blueprint = true, chesspiece_butterfly_marble = true, lavaarena_armor_hpdamager = true, barnacle = true, antchovies = true, quagmire_tomato_cooked = true, dragonpie_spice_sugar = true, chesspiece_antlion_marble = true, oceanfish_small_6 = true, deer_blue = true, oceanfishingbobber_robin_tacklesketch = true, waxwelljournal = true, walrus_tusk = true, deer = true, cookedmonstermeat = true, quagmire_spotspice_shrub = true, armorgrass = true, amulet_blueprint = true, wereitem_moose = true, purplemooneye = true, winter_ornament_plain5 = true, trinket_39 = true, rook_nightmare = true,
    oceanfish_small_1 = true, trinket_21 = true, torch = true, wormlight = true, mushroom_light2 = true, salsa_spice_salt = true, evergreen_stump = true, halloweencandy_8 = true, chesspiece_toadstool_moonglass = true, telebase_blueprint = true, wobysmall = true, butterflymuffin_spice_salt = true, quagmire_pond_salt = true, lavaarena_armorextraheavy = true, atrium_statue_facing = true, meatballs_spice_chili = true, quagmire_turnip = true, butterflymuffin_spice_sugar = true, bearger_fur = true, koalefant_winter = true, foliage = true, seastack = true, staff_tornado = true, thulecite_pieces = true, forge_abigail = true, moon_tree_blossom_worldgen = true, quagmire_food_058 = true, nitre = true, ruins_bat = true, yotc_carrat_scale_item = true, axe = true, batwing = true, quagmire_food_003 = true, marbleshrub_normal = true, basalt_pillar = true, lavaarena_battlestandard_shield = true, sewing_tape = true, ghostlyelixir_slowregen = true, tomato = true, frontend = true, oceanfish_medium_6 = true, trinket_7 = true, flower_rose = true, seafaring_blueprint = true, beebox_hermit = true, crow = true, chesspiece_moosegoose = true, chesspiece_stalker_moonglass = true, winter_ornament_boss_moose = true, quagmire_sap = true,
    rubble_low = true, van_poisonbirchnut = true, kabobs_spice_garlic = true, tallbirdegg_cooked = true, quagmire_potato_planted = true, resurrectionstatue = true, beetletaur = true, chesspiece_moon_stone = true, voltgoatjelly_spice_garlic = true, quagmire_food_066 = true, lavaarena_armor_hpextraheavy = true, lichen = true, arrowsign_post_blueprint = true, beehive = true, humanmeat_cooked = true, chesspiece_dragonfly_sketch = true, chessjunk2 = true, lava_pond_rock4 = true, brokentool = true, fast_farmplot = true, grass = true, van_rocky = true, splintmail = true, lavaarena_elemental = true, quagmire_old_rubble = true, backpack = true, quagmire_plate_silver = true, halloweenpotion_sparks_buff = true, frogglebunwich_spice_garlic = true, quagmire_food_047 = true, eyeplant = true, kelp = true, slurtle_shellpieces = true, sculptingtable_blueprint = true, chesspiece_anchor_stone = true, oceanfishingbobber_ball_tacklesketch = true, winter_ornament_plain6 = true, multiplayer_portal_moonrock_constr_plans = true, purplegem = true, quagmire_merm_cart2 = true, froglegs_cooked = true, yotc_carrat_race_finish = true, bundle = true, watermelonicle_spice_chili = true, fishsticks = true, shadowheart = true, papyrus = true, turf_fungus = true, waffles = true, bonesoup_spice_sugar = true,
    lobsterdinner_spice_chili = true, vegstinger_spice_chili = true, armormarble = true, quagmire_garlic_planted = true, glowberrymousse = true, snapper = true, driftwood_log = true, quagmire_rubble_bike = true, rope_blueprint = true, ceviche = true, sleepbomb_blueprint = true, deer_antler1 = true, boat_item = true, trinket_34 = true, monstermeat_dried = true, oceanfishingrod = true, meatballs_spice_sugar = true, taffy_spice_chili = true, flowerhat = true, tools_blueprint = true, flowersalad = true, rhinodrill2 = true, nightmarepie_spice_garlic = true, van_bishop_charge = true, moonrockidol = true, diviningrod = true, chesspiece_stalker_sketch = true, gears = true, dragonpie_spice_salt = true, endtable = true, quagmire_food_059 = true, fruitmedley = true, chesspiece_hornucopia_stone = true, trinket_31 = true, moonspider_spike = true, quagmire_soil = true, quagmire_sapbucket = true, quagmire_lamp_short = true, jellybean_spice_garlic = true, corn = true, babybeefalo = true, chesspiece_dragonfly_stone = true, halloweenpotion_health_large = true, chesspiece_klaus_stone = true, halloween_ornament_2 = true, asparagussoup_spice_garlic = true, mast_malbatross_item = true, bundle_container = true, stuffedeggplant = true, quagmire_wheat_planted = true,
    waterplant_rock = true, pigking = true, chessjunk1 = true, trinket_23 = true, nightsword = true, spice_salt = true, jaggedarmor = true, moonrockseed = true, teenbird = true, spear_wathgrithr = true, winter_twiggytree = true, shadow_knight = true, watermelonicle_spice_sugar = true, jammypreserves_spice_chili = true, freshfruitcrepes_spice_garlic = true, barnaclinguine_spice_garlic = true, oceanfishinglure_spinner_green = true, pondfish = true, unagi = true, ceviche_spice_salt = true, tacklecontainer = true, flowerheadband = true, trophyscale_fish = true, stalker_bulb_double = true, quagmire_seedpacket_5 = true, mushtree_medium_stump = true, powcake_spice_garlic = true, taffy_spice_sugar = true, fishmeat_small_cooked = true, wovengarland = true, quagmire_food_039 = true, lavaarena_groundliftrocks = true, moon_tree_normal = true, quagmire_lamp_post = true, messagebottleempty = true, mushroombomb = true, kabobs_spice_salt = true, battlestandard_damager_friendly = true, mushroom_light = true, chesspiece_anchor_moonglass = true, halloweenpotion_sanity_large = true, trailmix_spice_sugar = true, spiderhole = true, slurper_pelt = true, chesspiece_dragonfly = true, footballhat = true, nightsword_blueprint = true, mapscroll = true, moon_tree = true, goldenshovel = true,
    quagmire_food_021 = true, lavaarena_armorheavy = true, glommer = true, lightninggoat = true, ruinsrelic_table_blueprint = true, oceanfishinglure_spoon_brown = true, roastturkey = true, wobster_sheller_dead_cooked = true, chesspiece_butterfly = true, chesspiece_moon_sketch = true, dug_berrybush2 = true, cartographydesk_blueprint = true, bonestew_spice_garlic = true, wormwood = true, winter_ornament_plain8 = true, winterhat_blueprint = true, turf_road = true, honeynuggets_spice_garlic = true, gargoyle_hounddeath = true, moon_fissure_fx = true, blueamulet_blueprint = true, quagmire_parkspike_short = true, spider_dropper = true, yotc_seedpacket = true, mandrakesoup_spice_salt = true, rock2 = true, oceanfishingbobber_robin_winter_floater = true, antlion = true, oceanfishingbobber_robin_floater = true, rabbithouse_blueprint = true, lavaarena_spectator = true, quagmire_crate = true, trap_starfish = true, wintersfeastoven_blueprint = true, nightstick_blueprint = true, firebomb = true, meatrack_hermit = true, lifeinjector = true, honeyham = true, stuffedeggplant_spice_salt = true, quagmire_food_007 = true, amulet = true, pomegranate = true, papyrus_blueprint = true, chesspiece_moon_moonglass = true, mastupgrade_lightningrod = true, tamales = true, deer_antler3 = true, fruitmedley_spice_sugar = true, lost_toy_1 = true,
    lavaarena_bernie = true, oceanfish_medium_8 = true, marsh_bush = true, potatotornado_spice_chili = true, farmrock = true, bonestew = true, quagmire_food_022 = true, abigail_flower = true, quagmire_food_023 = true, yotc_carrat_race_checkpoint = true, quagmire_pigeon = true, leafymeatburger_spice_chili = true, clayhound = true, beequeen = true, cookedmeat = true, cutstone_blueprint = true, saltbox_blueprint = true, rocky = true, turf_underrock = true, winter_treestand = true, winter_ornament_fancy2 = true, portableblender_item = true, winter_ornament_fancy1 = true, watermelonicle_spice_garlic = true, perogies_spice_salt = true, quagmire_seedpacket = true, quagmire_food_bowl_goop = true, quagmire_food_054 = true, flower = true, green_mushroomhat_blueprint = true, leafloaf = true, tallbirdegg_cracked = true, winter_ornament_fancy8 = true, malbatross_feathered_weave = true, chesspiece_anchor_sketch_blueprint = true, quagmire_salt_rack_item = true, quagmire_altar_queen = true, winter_treestand_blueprint = true, steadfastgrandarmor = true, cookedsmallmeat = true, tacklesketch = true, quagmire_food_064 = true, dummytarget = true, klaus = true, oceanfish_medium_7 = true, kelphat = true, moonbutterflywings = true, rock_avocado_fruit_ripe = true, tomato_seeds = true, fish = true,
    chesspiece_moon_marble = true, minisign_drawn = true, cookedmandrake = true, lavaarena_rechargerhat = true, oceanfishingbobber_oval = true, bugnet = true, cartographydesk = true, chesspiece_moon = true, pigelite4 = true, dropperweb = true, frogglebunwich_spice_sugar = true, compass = true, adult_flytrap = true, goatmilk = true, oceanfishinglure_hermit_heavy_tacklesketch = true, mosquitosack = true, rope = true, hivehat = true, petals_evil = true, quagmire_coin3 = true, moon_altar_crown = true, spider_hider = true, quagmire_food_049 = true, spoiled_food = true, turf_fungus_red = true, marblebean_sapling = true, honeynuggets_spice_sugar = true, watermelonhat = true, plantmeat = true, cookpot_blueprint = true, reedtunic = true, mushtree_tall = true, lavaarena_portal_activefx = true, oar = true, krampus = true, gridplacer = true, cookiecutter = true, quagmire_mushroomstump = true, ghostlyelixir_attack = true, livingtree_halloween = true, chesspiece_carrat_marble = true, lava_pond_rock3 = true, nightmarelight = true, featheredtunic = true, table_winters_feast_blueprint = true, cutlichen = true, ruinsrelic_chipbowl_blueprint = true, fruitmedley_spice_chili = true, compostwrap = true, pepper_cooked = true,
    oceanfishinglure_spinner_white = true, chesspiece_crabking_stone = true, turf_dragonfly = true, icebox_blueprint = true, quagmire_salmon = true, monkeybarrel = true, rock_petrified_tree_short = true, antchovies_group = true, carrot_cooked = true, succulent_plant = true, rainhat = true, houndmound = true, wes = true, houndwhistle = true, featherfan = true, livingtree_root = true, yotc_carrat_gym_direction_item = true, wobster_sheller = true, oceanfishinglure_spoon_blue = true, pumpkincookie_spice_garlic = true, durian_seeds = true, fishmeat_cooked = true, quagmire_food_bowl_burnt = true, mandrakesoup_spice_garlic = true, teleportato_potato = true, dragonfruit = true, frogglebunwich = true, gravestone = true, winter_ornament_fancy7 = true, dragonpie = true, raincoat = true, gnarwail_water_shadow = true, ruinsrelic_chair_blueprint = true, frogfishbowl_spice_salt = true, hermithouse_construction3 = true, perdfan = true, vegstinger = true, quagmire_portal = true, livingtree = true, butterflymuffin_spice_garlic = true, barnaclesushi_spice_salt = true, lureplantbulb = true, quagmire_food_plate_goop = true, quagmire_coin4 = true, yotc_carrat_race_checkpoint_item = true, stalagmite_full = true, reviver = true, ruins_statue_mage_nogem = true, turf_meteor = true, greengem = true,
    monkey = true, pumpkin_lantern = true, spiderden_2 = true, blue_cap = true, guacamole_spice_salt = true, quagmire_food_024 = true, oceanfish_medium_1 = true, ruins_rubble_chair = true, deserthat = true, hermithouse_construction2 = true, lantern_blueprint = true, chesspiece_stalker_stone = true, waterplant = true, canary = true, nightlight_blueprint = true, ceviche_spice_garlic = true, halloween_ornament_4 = true, jellybean_spice_chili = true, fossil_piece = true, lost_toy_43 = true, mound = true, marblebean = true, evergreen_sparse_tall = true, quagmire_portal_key = true, moonglass_rock = true, barnaclepita_spice_salt = true, lava_pond_rock = true, unagi_spice_garlic = true, trailmix = true, quagmire_food_010 = true, mulleddrink = true, surfnturf_spice_garlic = true, deciduoustree_normal = true, quagmire_rubble_chimney2 = true, winter_ornament_plain9 = true, halloweenpotion_sparks = true, beebox_blueprint = true, mermhouse = true, hallowed_nights_event_global = true, meatysalad_spice_chili = true, livingstaff = true, barnaclinguine_spice_sugar = true, winters_feast_event_frontend = true, gazpacho = true, winter_tree = true, abigailforcefieldretaliation = true, toadstool = true, twiggy_tall = true, beequeenhivegrown = true, bonesoup_spice_chili = true,
    reskin_tool = true, bernie_active = true, silkengrandarmor = true, madscience_lab_blueprint = true, ruins_vase = true, quagmire_food_043 = true, jellybean_spice_sugar = true, monstertartare = true, lavae_cocoon = true, hammer_mjolnir = true, squid = true, halloweenpotion_embers = true, webber_spider_minion = true, spice_sugar = true, cactus_meat_cooked = true, mushroom_light2_blueprint = true, cave_fern = true, halloween_ornament_1 = true, quagmire_trader_merm = true, monsterlasagna = true, stick = true, lost_toy_19 = true, chesspiece_pipe_stone = true, lavaarena_keyhole = true, oceanfishingbobber_ball = true, ruinsrelic_bowl = true, stalker_forest = true, trinket_43 = true, animal_track = true, pigskin = true, rock_petrified_tree = true, oceanfishableflotsam = true, fireflies = true, monstertartare_spice_garlic = true, pocket_scale = true, spiderqueen = true, chesspiece_deerclops_marble = true, quagmire_park_angel2 = true, deer_red = true, quagmire_food_019 = true, refine_blueprint = true, quagmire_mealingstone = true, lavaarena_lucy = true, statueglommer = true, pigshrine_blueprint = true, deerclops_eyeball = true, pond_cave = true, mast_item_blueprint = true, winter_food5 = true, winter_food3 = true,
    winter_ornament_boss_deerclops = true, malbatross_feather_fall = true, garlic = true, asparagussoup_spice_chili = true, dug_sapling_moon = true, durian = true, dug_trap_starfish = true, oceanfishableflotsam_water = true, lavae_egg = true, beardhair = true, merm = true, winona_spotlight_head = true, watermelon_cooked = true, cactus_flower = true, marblepillar = true, atrium_overgrowth = true, stalker_atrium = true, quagmire_onion = true, transistor = true, quagmire_mushrooms_cooked = true, barnaclinguine = true, singingshell_octave3 = true, magic_blueprint = true, voltgoatjelly_spice_salt = true, oceanfishinglure_spinner_yellow = true, evergreen_short = true, icecream_spice_garlic = true, beefalohat_blueprint = true, icestaff_blueprint = true, homesign_blueprint = true, blueamulet = true, quagmire_beefalo = true, lavaarena_armormedium = true, chesspiece_beequeen = true, chesspiece_pipe = true, winona_catapult = true, eggplant = true, dragonpie_spice_chili = true, tumbleweed = true, van_icehound = true, moondial = true, honeynuggets_spice_salt = true, feather_robin = true, meatballs = true, turf_grass = true, stalagmite_tall = true, bird_egg = true, halloweencandy_5 = true, mastupgrade_lamp = true, moon_altar_glass = true,
    turkeydinner_spice_sugar = true, armor_bramble = true, silkenarmor = true, plantmeat_cooked = true, bonestew_spice_salt = true, glasscutter = true, town_blueprint = true, quagmire_pot_small = true, surfnturf_spice_sugar = true, lavaarena_lightdamagerhat = true, armorwood_blueprint = true, coldfire_blueprint = true, flint = true, kabobs_spice_sugar = true, fence_item = true, mooseegg = true, fishtacos_spice_garlic = true, lavaarena_groundliftwarning = true, seeds = true, reeds = true, tent_blueprint = true, green_mushroomhat = true, ceviche_spice_chili = true, strawhat = true, mashedpotatoes_spice_garlic = true, carrat = true, pumpkin_cooked = true, footballhat_blueprint = true, trinket_44 = true, winter_ornament_plain3 = true, lifeinjector_blueprint = true, winterhat = true, quagmire_altar_statue2 = true, quagmire_food_013 = true, bonesoup_spice_salt = true, butter = true, winter_ornament_festivalevents2 = true, rainhat_blueprint = true, portablespicer = true, mushroombomb_dark = true, flower_cave = true, turkeydinner = true, diviningrodbase = true, sculpture_rooknose = true, turf_road_blueprint = true, red_mushroom = true, walrushat = true, lavaarena_feathercrownhat = true, quagmire_swampig_house = true, bird_egg_cooked = true,
    moonglass = true, smallmeat = true, tallbirdnest = true, wormhole = true, multiplayer_portal_moonrock_constr = true, quagmire_food_014 = true, lava_pond_rock7 = true, tourtiere = true, atrium_light_light = true, lobsterdinner_spice_garlic = true, dragonheadhat = true, quagmire_pot_syrup = true, greenamulet = true, wereitem_beaver = true, quagmire_altar_statue1 = true, madscience_lab = true, quagmire_food_006 = true, war_blueprint = true, quagmire_food_051 = true, glassspike_short = true, gnarwail_attack_horn = true, quagmire_salmon_cooked = true, wall_wood_item_blueprint = true, quagmire_seedpacket_3 = true, hotchili_spice_sugar = true, wathgrithrhat = true, chesspiece_pawn_marble = true, pandoraschest = true, blue_mushroomhat = true, quagmire_pebblecrab = true, opalstaff = true, moonbutterfly_sapling = true, birdtrap = true, quagmire_seedpacket_6 = true, phlegm = true, lavaarena_fest_frontend = true, trinket_20 = true, chesspiece_muse = true, waffles_spice_salt = true, mean_flytrap = true, oceanfishingbobber_robin = true, surfnturf_spice_salt = true, potatosouffle_spice_salt = true, dead_sea_bones = true, winter_ornament_boss_antlion = true, quagmire_coin2 = true, ancient_altar_broken = true, quagmire_planted_soil_front = true, sacred_chest = true, chesspiece_crabking_sketch = true,
    crawlinghorror = true, oar_blueprint = true, lavaarena_lootbeacon = true, resurrectionstone = true, fence_item_blueprint = true, van_slurper = true, dragonfruit_cooked = true, driftwood_small1 = true, fruitmedley_spice_garlic = true, twiggy_old = true, icecream_spice_chili = true, chesspiece_klaus = true, leif = true, rock_petrified_tree_old = true, mermthrone = true, perogies = true, thulecite = true, moonrocknugget = true, onemanband_blueprint = true, giftwrap = true, stalagmite_med = true, armor_sanity_blueprint = true, forge_trident = true, ratatouille_spice_sugar = true, battlestandard_heal_friendly = true, gravy = true, abigail_attack_fx_ground = true, mermhat = true, coontail = true, pigman = true, quagmire_turnip_planted = true, oceanfishinglure_spoon_green = true, lavaarena_battlestandard_damager = true, pigelitefighter2 = true, malbatross_feathered_weave_blueprint = true, penguin_ice = true, mushtree_medium = true, salsa_spice_chili = true, chesspiece_pawn_sketch = true, turf_pebblebeach = true, farm_blueprint = true, polishcookie = true, tornado = true, eggplant_cooked = true, yotc_carrat_gym_stamina = true, nightlight = true, klaussackkey = true, honeycomb = true, spore_small = true, trinket_45 = true,
    leafymeatburger = true, trails2 = true, none_event_frontend = true, eyebrellahat_blueprint = true, salsa_spice_sugar = true, lavaarena_seeddart2 = true, blue_cap_cooked = true, quagmire_casseroledish = true, winch_blueprint = true, waxwell = true, boards_blueprint = true, armorwood = true, tentacle_pillar = true, lavaarena_spawner = true, meatysalad = true, stalker_berry = true, latkes = true, plant_normal = true, waterplant_spawner_rough = true, researchlab2_blueprint = true, turf_savanna = true, winters_feast_event_global = true, quagmire_slaughtertool = true, trunkvest_winter_blueprint = true, quagmire_smallmeat = true, quagmire_food_050 = true, dragonchilisalad_spice_garlic = true, stalker_bulb = true, onion_cooked = true, saltlick_blueprint = true, quagmire_pot = true, winter_food6 = true, tacklestation_blueprint = true, trunkvest_summer_blueprint = true, turf_checkerfloor_blueprint = true, rock_flintless_med = true, critter_kitten = true, evergreen_sparse_normal = true, boomerang_blueprint = true, baconeggs_spice_chili = true, year_of_the_carrat_event_frontend = true, malbatross = true, upper_nightmarefissurefx = true, chesspiece_malbatross_moonglass = true, surfnturf = true, winter_ornament_light3 = true, wormlight_lesser = true, rock_petrified_tree_tall = true, mermhouse_crafted = true, beargervest = true,
    powcake_spice_chili = true, anchor_item = true, teleportato_ring = true, winter_ornament_fancy5 = true, moon_tree_tall = true, jammypreserves_spice_sugar = true, potatosouffle = true, lavaarena_eyecirclethat = true, chesspiece_antlion_sketch = true, blowdart_lava = true, mermhead = true, trinket_11 = true, yotc_carrat_race_start_item = true, turkeydinner_spice_salt = true, winter_ornament_light5 = true, quagmire_planted_soil_back = true, lobsterbisque = true, winter_ornament_boss_dragonfly = true, spice_garlic = true, petrifyingtome = true, vegstinger_spice_garlic = true, trinket_40 = true, quagmire_sugarwoodtree = true, krampus_sack = true, cutstone = true, eyeturret = true, gift = true, wolfgang = true, penguin = true, pighouse_blueprint = true, trunk_cooked = true, mushtree_small = true, book_sleep = true, rock_flintless = true, winter_food1 = true, lobsterdinner_spice_sugar = true, blue_mushroomhat_blueprint = true, quagmire_swampigelder = true, atrium_light = true, pumpkinpie = true, reskin_tool_blueprint = true, webber = true, fishtacos_spice_chili = true, critter_lamb = true, dragonbodyhat = true, rabbit = true, chessjunk = true, smallmeat_dried = true, critter_puppy = true, leafymeatsouffle_spice_garlic = true,
    frogfishbowl = true, barnaclesushi = true, critterlab = true, pigelitefighter3 = true, flower_cave_double = true, spiderhole_rock = true, seafoodgumbo_spice_sugar = true, boatpatch_blueprint = true, quagmire_cookedsmallmeat = true, bedroll_furry_blueprint = true, seafoodgumbo_spice_salt = true, jammypreserves_spice_salt = true, deerclops = true, pumpkincookie_spice_chili = true, perogies_spice_sugar = true, vegstinger_spice_salt = true, bernie_inactive = true, asparagus = true, cavein_boulder = true, fishmeat_small = true, miniflare_minimap = true, pepperpopper = true, oceanfishingbobber_robin_winter = true, onion_seeds = true, lavae_pet = true, perd = true, lavaarena_gauntlet = true, quagmire_rubble_carriage = true, minisign_item = true, poop = true, monsterlasagna_spice_salt = true, shadowdigger = true, mastupgrade_lamp_item_blueprint = true, tentacle = true, unagi_spice_salt = true, lavaarena_boarlord = true, oceanfish_medium_3 = true, watermelonhat_blueprint = true, kelp_cooked = true, chesspiece_pawn_stone = true, halloweenpotion_moon = true, meatrack_blueprint = true, hutch_fishbowl = true, nightmarepie_spice_sugar = true, stuffedeggplant_spice_chili = true, shadowhand = true, lavalight = true, stalker = true, cave_entrance_open = true, halloweencandy_12 = true,
    lost_toy_10 = true, glowberrymousse_spice_sugar = true, quagmire_food_041 = true, rook = true, chesspiece_muse_stone = true, quagmire_food_036 = true, waterplant_base = true, fruitdragon = true, nightmarefuel = true, trinket_38 = true, wetgoop_spice_sugar = true, rocks = true, gargoyle_werepighowl = true, lavaarena_groundliftembers = true, birdtrap_blueprint = true, pinecone = true, goggleshat_blueprint = true, winter_ornament_boss_bearger = true, oceanfishingbobber_goose = true, year_of_the_pig_event_global = true, pepperpopper_spice_salt = true, bishop_nightmare = true, quagmire_campfire = true, halloweenpotion_sanity_small = true, glommerflower = true, glowberrymousse_spice_garlic = true, sewing_kit_blueprint = true, rock_avocado_bush = true, shadowduelist = true, singingshell_octave4 = true, ruins_bowl = true, cactus = true, robin = true, boatfragment05 = true, quagmire_rubble_roof = true, oceanfish_medium_4 = true, miniboatlantern = true, lobsterdinner_spice_salt = true, spiralspear = true, mermguard = true, ruins_chair = true, chesspiece_formal_sketch = true, featherpencil = true, salsa_spice_garlic = true, yotp_food1 = true, noxhelm = true, sculptingtable = true, anchor_item_blueprint = true, quagmire_food_026 = true, turf_fungus_green = true,
    dress_blueprint = true, chesspiece_moosegoose_sketch = true, carrot_seeds = true, seafoodgumbo_spice_garlic = true, sketch = true, quagmire_rubble_house = true, van_pig = true, burnt_marsh_bush = true, baconeggs_spice_salt = true, feather_robin_winter = true, pigshrine = true, watermelon_seeds = true, halloweencandy_10 = true, meatballs_spice_salt = true, quagmire_food_048 = true, pillar_atrium = true, chesspiece_clayhound_stone = true, van_leif = true, moqueca = true, houndfire = true, monstertartare_spice_sugar = true, ruins_rubble_vase = true, lavae = true, dug_sapling = true, wobster_sheller_dead = true, bananapop = true, razor = true, oceanfishingbobber_plug_floater = true, trinket_17 = true, wall_moonrock_item = true, fishingrod = true, singingshell_octave5 = true, bushhat = true, chesspiece_stalker = true, basalt = true, trinket_12 = true, sweetpotato = true, gemsocket = true, oceanfish_small_7 = true, hutch = true, perogies_spice_garlic = true, monstertartare_spice_chili = true, redmooneye = true, yellowstaff = true, rhinodrill = true, quagmire_garlic = true, batbat = true, glowberrymousse_spice_chili = true, chesspiece_rook_moonglass = true, abigailforcefield = true,
    van_spider_hider = true, stickright = true, pitchfork_blueprint = true, quagmire_food_031 = true, brokenwall_ruins = true, yotc_carrat_gym_reaction_item = true, oceanfishingbobber_oval_floater = true, red_mushroomhat = true, winter_ornament_boss_krampus = true, sewing_kit = true, sunkenchest = true, wetgoop_spice_salt = true, minerhat = true, moonspiderden = true, quagmire_merm_cart1 = true, rock1 = true, light_blueprint = true, leafymeatsouffle_spice_chili = true, winona_battery_high = true, lost_toy_2 = true, siestahut = true, unagi_spice_sugar = true, chesspiece_crabking = true, moqueca_spice_salt = true, icecream_spice_sugar = true, firestaff = true, pitchfork = true, asparagussoup_spice_salt = true, winter_ornament_plain7 = true, quagmire_food_068 = true, oceanfish_small_3 = true, quagmire_crate_grill_small = true, tallbird = true, boards = true, treasurechest = true, twiggy_normal = true, watermelonicle = true, fissure_lower = true, walterhat = true, messagebottletreasure_marker = true, pottedfern_blueprint = true, depleted_grass = true, chesspiece_formal_moonglass = true, dragonfly = true, onemanband = true, gazpacho_spice_sugar = true, atrium_fence = true, quagmire_seedpacket_mix = true, dragonflyfurnace_blueprint = true, voltgoatjelly = true,
    ratatouille_spice_garlic = true, honeynuggets = true, resurrectionstatue_blueprint = true, quagmire_food_034 = true, halloweencandy_13 = true, saddle_race = true, mastupgrade_lightningrod_item = true, armordragonfly = true, wobster_sheller_land = true, mossling = true, van_spider_moon = true, chesspiece_knight = true, van_minotaur = true, quagmire_onion_cooked = true, icehat = true, thurible = true, rabbithouse = true, eyeturret_base = true, rhinobuff = true, moon_tree_blossom = true, van_poisonbirchnut_root = true, terrorbeak = true, quagmire_pot_hanger_item = true, quagmire_seeds_2 = true, shadowmeteor = true, winter_food8 = true, spice_chili = true, turkeydinner_spice_chili = true, feather_crow = true, quagmire_turnip_cooked = true, brokenwall_wood = true, endtable_blueprint = true, blacksmithsedge = true, infernalstaff = true, atrium_gate = true, rock_avocado_fruit_sprout = true, chesspiece_clayhound_sketch = true, meat = true, goldenshovel_blueprint = true, trinket_28 = true, lava_pond = true, quagmire_portal_activefx = true, warg_gooicing = true, quagmire_saltrock = true, trinket_4 = true, mushroom_farm_blueprint = true, cabbagerolls = true, mutatedhound = true, ruins_chipbowl = true, carrot_planted = true,
    yellowmooneye = true, halloweencandy_2 = true, arrowsign_post = true, saddle_basic_blueprint = true, marbleshrub_short = true, halloween_ornament_5 = true, lumpy_sapling = true, fishtacos = true, winterometer_blueprint = true, mandrake_active = true, quagmire_food_067 = true, fish_box_blueprint = true, moon_altar_seed = true, fencepost = true, lavaarena_crowndamagerhat = true, leafymeatburger_spice_garlic = true, quagmire_fern = true, van_spider_spitter = true, butterfly = true, quagmire_bowl_silver = true, moon_altar_rock_glass = true, berrybush2 = true, slingshotammo_slow = true, shovel_blueprint = true, quagmire_potato_cooked = true, researchlab2 = true, chesspiece_formal = true, sweatervest_blueprint = true, trinket_24 = true, shovel = true, seafaring_prototyper = true, winter_ornament_festivalevents1 = true, acorn = true, chesspiece_formal_stone = true, minerhat_blueprint = true, fossilspike2 = true, turf_dragonfly_blueprint = true, grassgekko = true, frogfishbowl_spice_garlic = true, oar_driftwood_blueprint = true, bearger_fur_blueprint = true, trinket_26 = true, moon_fissure_plugged = true, monsterlasagna_spice_garlic = true, pepperpopper_spice_garlic = true, leafymeatsouffle_spice_salt = true, dragonchilisalad = true, nightmarelightfx = true, royal_jelly = true, moonbase = true,
    quagmire_food_028 = true, oceanfishingbobber_canary_floater = true, quagmire_carrot_cooked = true, moonrock_pieces = true, van_spider = true, fishsticks_spice_sugar = true, lavaarena_tiaraflowerpetalshat = true, guacamole_spice_garlic = true, lighter = true, brokenwall_moonrock = true, twigs = true, yotc_carrat_gym_stamina_item = true, hermit_bundle_shells = true, fish_cooked = true, ratatouille_spice_chili = true, quagmire_food_020 = true, pillar_cave_rock = true, mandrake_planted = true, chesspiece_clayhound_moonglass = true, bullkelp_root = true, leafymeatburger_spice_salt = true, sentryward = true, coldfire = true, quagmire_food_052 = true, moqueca_spice_sugar = true, statue_marble_pawn = true, moonrockseed_icon = true, jellybean_spice_salt = true, winter_ornament_light4 = true, chesspiece_malbatross_sketch = true, pillar_stalactite = true, wall_hay_item = true, lavaarena_strongdamagerhat = true, chesspiece_crabking_moonglass = true, lobsterbisque_spice_sugar = true, manrabbit_tail = true, beehat_blueprint = true, chesspiece_antlion_stone = true, slingshotammo_rock = true, beequeenhive = true, chesspiece_deerclops_moonglass = true, purpleamulet = true, balloon = true, yotc_seedpacket_rare = true, marbletree_1 = true, van_winterkoalefant = true, pumpkincookie = true, marbletree_4 = true, none_event_global = true, farmrocktall = true,
    trap_teeth_blueprint = true, mashedpotatoes = true, barnaclepita_spice_garlic = true, frogfishbowl_spice_sugar = true, quagmire_spotspice_sprig = true, van_spider_dropper = true, guacamole_spice_chili = true, chesspiece_stalker_marble = true, quagmire_food_033 = true, lobsterbisque_spice_salt = true, portabletent_item = true, chesspiece_malbatross = true, lavaarena_armorlight = true, seastack_spawner_rough = true, ruins_statue_head = true, cave_banana_burnt = true, chesspiece_bishop = true, trinket_1 = true, rudder = true, rubble_med = true, trinket_19 = true, slurper = true, winter_food9 = true, lavaarena_armorlightspeed = true, sculpture_knighthead = true, yotc_carrat_gym_speed = true, chesspiece_muse_sketch = true, trap = true, quagmire_seeds_1 = true, evergreen = true, shadowlumber = true, moon_altar_idol = true, trinket_27 = true, lavaarena_seeddarts = true, mole = true, walrus = true, oasislake = true, halloweencandy_9 = true, turf_carpetfloor_blueprint = true, rock_moon = true, gargoyle_werepigatk = true, quagmire_food_001 = true, dug_berrybush_juicy = true, quagmire_sap_spoiled = true, chesspiece_claywarg = true, portablespicer_item = true, chessjunk3 = true, perogies_spice_chili = true, oceanfish_medium_5 = true, teleportato_base = true,
    statue_marble = true, anchor = true, waffles_spice_sugar = true, warly = true, chesspiece_malbatross_stone = true, oceanfishinglure_spoon_yellow = true, chesspiece_bearger_sketch = true, waxwell_shadowstriker = true, forge_trap_spikes = true, saltrock = true, pumpkin = true, buzzardspawner = true, cave_hole = true, quagmire_casseroledish_small = true, sculpture_bishophead = true, gnarwail = true, gargoyle_houndatk = true, chesspiece_moosegoose_moonglass = true, wasphive = true, icehat_blueprint = true, honey = true, quagmire_grill_small_item = true, catcoonden = true, quagmire_food_005 = true, van_deerclops = true, twiggy_nut_sapling = true, yotc_carrat_gym_speed_item = true, slingshotammo_thulecite = true, kabobs_spice_chili = true, bacontome = true, oceanfishingbobber_goose_floater = true, bathbomb = true, pigelite1 = true, fishtacos_spice_salt = true, beeswax_blueprint = true, passive_shadow_fx = true, wintersfeastoven = true, healingsalve = true, pigelite2 = true, boatfragment04 = true, slow_farmplot = true, cave_banana_cooked = true, heatrock = true, evergreen_sparse = true, coldfirepit = true, quagmire_crabmeat_cooked = true, chesspiece_toadstool_sketch = true, chesspiece_dragonfly_marble = true, cookiecutterhat = true, bananapop_spice_sugar = true,
    perdshrine = true, quagmire_food_044 = true, fishingrod_blueprint = true, yotp_food3 = true, spear_blueprint = true, beefalowool = true, winter_ornament_boss_noeyeblue = true, armordragonfly_blueprint = true, twiggy_short = true, trinket_15 = true, waxpaper = true, armorslurper = true, pomegranate_cooked = true, chesspiece_bearger_marble = true, bonesoup = true, yotc_carratshrine = true, deciduoustree_burnt = true, sculpture_bishopbody = true, winona_battery_low = true, powcake_spice_sugar = true, oasis_cactus = true, ruins_rubble_table = true, mushtree_tall_webbed = true, miniflare = true, sandblock = true, mandrakesoup_spice_sugar = true, ruinsrelic_bowl_blueprint = true, burntstickleft = true, chesspiece_muse_moonglass = true, quagmire_food_042 = true, chesspiece_beequeen_sketch = true, dug_rock_avocado_bush = true, hotchili_spice_garlic = true, chesspiece_deerclops_stone = true, lobsterbisque_spice_chili = true, stuffedeggplant_spice_garlic = true, wargshrine = true, quagmire_portal_bubblefx = true, chesspiece_muse_marble = true, fossil_piece_clean = true, mastupgrade_lightningrod_item_blueprint = true, year_of_the_pig_event_backend = true, rock_moon_shell = true, earmuffshat_blueprint = true, boatfragment03 = true, steadfastarmor = true, slow_farmplot_blueprint = true, bullkelp_beachedroot = true, wall_stone_item = true, winter_ornament_boss_klaus = true,
    malbatross_beak = true, quagmire_book_fertilizer = true, hotspring = true, critter_glomling = true, sculpture_knightbody = true, greenmooneye = true, year_of_the_varg_event_frontend = true, book_tentacles = true, ash = true, bonestew_spice_chili = true, rainometer_blueprint = true, arrowsign_panel = true, chesspiece_rook_marble = true, quagmire_crate_oven = true, abigail_attack_fx = true, van_deerclopslaser = true, van_walrus = true, van_penguin = true, lava_pond_rock6 = true, van_rook = true, van_spiderqueen = true, van_spidermonkey = true, pigelitefighter4 = true, van_plant_root = true, froglegs = true, van_palmguard = true, redpouch_yotp = true, redpouch_yotc = true, fertilizer_blueprint = true, winter_ornament_plain4 = true, saltstack = true, featherpencil_blueprint = true, mandrake = true, lava_fissure = true, cutgrass = true, winter_ornament_light6 = true, steeringwheel = true, panettone = true, quagmire_fest_frontend = true, chesspiece_toadstool_stone = true, malbatross_feather = true, pillar_algae = true, hambat = true, giftwrap_blueprint = true, dug_marsh_bush = true, multiplayer_portal = true, quagmire_crabmeat = true, beemine = true, quagmire_food_037 = true, scarecrow_blueprint = true,
    dragonchilisalad_spice_chili = true, bernie_big = true, redlantern = true, yotc_carratshrine_blueprint = true, merm_guard = true, catcoon = true, frogfishbowl_spice_chili = true, log = true, forge_cookpot = true, marbleshrub_tall = true, asparagussoup = true, wobster_moonglass = true, moqueca_spice_chili = true, oceanfishinglure_spoon_silver = true, ruinsrelic_plate = true, sanityrock = true, forge_bernie = true, townportal = true, trap_teeth_maxwell = true, pillar_cave_flintless = true, redgem = true, winter_ornament_light1 = true, deciduoustree_short = true, trophyscale_fish_blueprint = true, walrus_camp = true, armorslurper_blueprint = true, lost_toy_14 = true, battlestandard_speed_friendly = true, stalker_minion1 = true, halloweencandy_6 = true, spoiled_fish = true, treasurechest_blueprint = true, battlestandard_shield_friendly = true, frog = true, forginghammer = true, battlestandard_heal = true, waterpump = true, battlestandard_damager = true, potatotornado_spice_salt = true, ghostlyelixir_speed = true, sisturn = true, pitpig = true, ghostlyelixir_shield = true, quagmire_evergreen = true, lavaarena_battlestandard_heal = true, marbletree_2 = true, spice_bomb = true, van_eyeplant = true, quagmire_garlic_cooked = true, brokenwall_stone = true,
    pickledherring = true, quagmire_spotspice_ground = true, quagmire_key = true, nightstick = true, teleport_staff = true, chesspiece_malbatross_marble = true, whip_blueprint = true, crystaltiara = true, piggyback_blueprint = true, quagmire_seeds_4 = true, slingshotammo_freeze = true, cookiecuttershell = true, resplendentnoxhelm = true, featheredwreath = true, blossomedwreath = true, quagmire_key_park = true, humanmeat = true, lantern = true, quagmire_tomato = true, boneshard = true, fissure = true, quagmire_seedpacket_4 = true, cave_entrance_ruins = true, guacamole = true, lureplant = true, jaggedgrandarmor = true, icecream_spice_salt = true, voltgoatjelly_spice_sugar = true, red_cap_cooked = true, chesspiece_beequeen_stone = true, earmuffshat = true, charcoal = true, crumbs = true, seedlingtome = true, winona = true, bananapop_spice_salt = true, driftwood_tall = true, moltendarts = true, chesspiece_dragonfly_moonglass = true, winter_ornament_boss_noeyered = true, vegstinger_spice_sugar = true, bandage = true, statueharp = true, forgedarts = true, sculpture_rookbody = true, yotp_food2 = true, turf_mud = true, yotc_carrat_scale = true, yotc_carrat_rug = true, oar_driftwood = true,
    wall_moonrock = true, houndbone = true, yotc_carrat_race_finish_item = true, atrium_idol = true, bee = true, evergreen_burnt = true, quagmire_food_069 = true, turtillus = true, mermwatchtower = true, wx78 = true, wurt = true, californiaroll_spice_garlic = true, lava_pond_rock5 = true, unagi_spice_chili = true, dirtpile = true, quagmire_swampig_house_rubble = true, wortox_soul = true, lavaarena_heavyblade = true, chesspiece_rook_stone = true, wortox_portal_jumpin_fx = true, lost_toy_42 = true, critter_perdling = true, barnaclepita = true, hotcold_fx = true, turf_checkerfloor = true, birchnutdrake = true, winter_ornament_festivalevents3 = true, chesspiece_bearger_stone = true, reflectivevest = true, siestahut_blueprint = true, whisperinggrandarmor = true, survival_blueprint = true, barnaclestuffedfishhead_spice_chili = true, catcoonhat = true, wormlight_plant = true, chesspiece_anchor_marble = true, moonbutterfly = true, chesspiece_bearger_moonglass = true, mushtree_tall_stump = true, oceanfishinglure_spinner_red = true, year_of_the_carrat_event_global = true, goggleshat = true, chesspiece_knight_moonglass = true, quagmire_altar_bollard = true, lavaarena_crowdstand = true, monsterlasagna_spice_chili = true, wormhole_limited_1 = true, canary_poisoned = true, waterpump_blueprint = true, telestaff_blueprint = true,
    wilson = true, worm = true, winter_deciduoustree = true, book_fossil = true, green_cap = true, lavaarena_abigail = true, propsign = true, wobster_den_spawner_shore = true, chesspiece_knight_sketch = true, wobster_den = true, mast_item = true, panflute = true, cactus_meat = true, chesspiece_bishop_sketch = true, wobster_moonglass_land = true, deciduoustree_stump = true, minotaur = true, spider_spitter = true, trinket_16 = true, icestaff = true, molehat_blueprint = true, halloween_ornament_6 = true, klaus_sack = true, deciduoustree = true, wall_ruins = true, flowersalad_spice_sugar = true, saddle_race_blueprint = true, winter_food4 = true, forcefieldfx = true, quagmire_potato = true, wortox_portal_jumpout_fx = true, butterflymuffin = true, meatysalad_spice_salt = true, hammer = true, hermit_bundle = true, oceanfishingbobber_twig_floater = true, trinket_42 = true, chesspiece_pawn = true, moonrockcrater = true, bluegem = true, berrysauce = true, festivefish = true, blueprint = true, gargoyle_werepigdeath = true, winterometer = true, halloweencandy_14 = true, glassblock = true, firecrackers = true, nightmarefuel_blueprint = true, potatosouffle_spice_garlic = true,
    oceanfish_small_8 = true, piggyback = true, chum = true, quagmire_food_017 = true, freshfruitcrepes_spice_chili = true, winter_ornament_plain10 = true, mushroomsprout = true, flytraptome = true, lost_toy_7 = true, lavae_tooth = true, moon_fissure = true, winter_ornament_boss_toadstool = true, pigguard = true, atrium_statue = true, winter_ornament_boss_beequeen = true, winter_ornament_festivalevents5 = true, winter_ornament_festivalevents4 = true, burntfencepostright = true, birdcage = true, portabletent = true, winter_ornament_light7 = true, winter_ornament_boss_malbatross = true, fishingnetvisualizer = true, corn_cooked = true, goldenpickaxe_blueprint = true, potato = true, winter_ornament_fancy6 = true, chesspiece_moosegoose_stone = true, winter_ornament_fancy4 = true, chesspiece_formal_marble = true, livingtree_sapling = true, mast_malbatross = true, halloweenpotion_embers_buff = true, oceanfish_small_4 = true, winter_ornament_plain12 = true, quagmire_food_032 = true, lavaarena_armormediumrecharger = true, deerclops_laserempty = true, clairvoyantcrown = true, teleportato_box = true, quagmire_carrot = true, chesspiece_claywarg_stone = true, van_flytrap = true, winter_ornament_plain1 = true, glassspike_tall = true, honeyham_spice_salt = true, winona_spotlight = true, barnaclinguine_spice_chili = true, californiaroll = true, minotaurhorn = true,
    drumstick = true, halloweencandy_11 = true, mermthrone_construction = true, skeleton = true, freshfruitcrepes = true, wickerbottom = true, barnaclesushi_spice_sugar = true, whip = true, lucy = true, wereitem_goose = true, chesspiece_beequeen_moonglass = true, wendy = true, mushroom_farm = true, taffy = true, quagmire_altar = true, mashedpotatoes_spice_chili = true, quagmire_syrup = true, lavaarena_floorgrate = true, quagmire_food_035 = true, guano = true, leafloaf_spice_sugar = true, waveyjones_marker = true, fishtacos_spice_sugar = true, pumpkincookie_spice_salt = true, scarecrow = true, pond_mos = true, boat_leak = true, waveyjones_hand_art = true, chesspiece_pipe_marble = true, catcoonhat_blueprint = true, bandage_blueprint = true, chesspiece_beequeen_marble = true, underwater_salvageable = true, stagehand = true, chesspiece_rook = true, chesspiece_bishop_moonglass = true, nightmarefissurefx = true, wathgrithr_bloodlustbuff_other = true, rainometer = true, wathgrithr = true, oceanfishinglure_hermit_rain = true, umbrella = true, orangeamulet = true, monsterlasagna_spice_sugar = true, battlestandard_shield = true, cane_blueprint = true, quagmire_food_015 = true, farmrockflat = true, orangegem = true, waterplant_planter = true,
    goldenaxe_blueprint = true, boaron = true, oceanfishinglure_hermit_snow = true, fish_box = true, ruinsrelic_chair = true, gingerbreadwarg = true, claywarg = true, wardrobe = true, walter = true, little_walrus = true, birdcage_blueprint = true, wall_ruins_item = true, pond_algae = true, wall_hay = true, wall_wood_item = true, wall_wood = true, hermit_cracked_pearl = true, chesspiece_butterfly_sketch = true, deciduous_root = true, wall_stone = true, purpleamulet_blueprint = true, lavaarena_abigail_flower = true, flower_withered = true, quagmire_seedpacket_2 = true, wobybig = true, wargshrine_blueprint = true, beehat = true, pillar_ruins = true, berries_cooked = true, surfnturf_spice_chili = true, berries = true, potato_seeds = true, armorsnurtleshell = true, watermelon = true, chesspiece_antlion = true, deerclops_laser = true, marbleshrub = true, kelp_dried = true, staffcoldlight = true, berries_juicy_cooked = true, halloweenpotion_health_small = true, healingsalve_blueprint = true, asparagussoup_spice_sugar = true, waterballoon_blueprint = true, eyebrellahat = true, puffin = true, migration_portal = true, quagmire_flour = true, onion = true, chesspiece_bearger = true,
    corn_seeds = true, marsh_tree = true, durian_cooked = true, trap_bramble = true, critter_lunarmothling = true, hawaiianshirt_blueprint = true, signleft = true, nightmarepie = true, cookiecutterhat_blueprint = true, icepack = true, waffles_spice_garlic = true, pepper_seeds = true, pepper = true, lavaarena_firebomb = true, carrot = true, armorruins = true, pumpkin_seeds = true, beefalohat = true, fossil_stalker = true, dragonfruit_seeds = true, winter_ornament_plain11 = true, quagmire_seeds_6 = true, leafymeatsouffle_spice_sugar = true, tomato_cooked = true, beargervest_blueprint = true, chesspiece_hornucopia_marble = true, quagmire_book_shadow = true, blowdart_lava2 = true, cookpot = true, gingerdeadpig = true, turf_shellbeach = true, quagmire_rubble_empty = true, koalefant_summer = true, turf_cave = true, pottedfern = true, saddle_war = true, monstermeat = true, mushtree_small_stump = true, turf_deciduous = true, spore_tall = true, butterflywings = true, saddle_basic = true, year_of_the_varg_event_global = true, turf_woodfloor = true, chesspiece_antlion_moonglass = true, oceanfishinglure_spinner_orange = true, turf_sinkhole = true, supertacklecontainer = true, trunkvest_winter = true, trunk_winter = true,
    trunk_summer = true, moon_altar_rock_idol = true, monstertartare_spice_salt = true, rubble = true, trinket_46 = true, planted_flower = true, evergreen_sparse_short = true, quagmire_hoe = true, freshfruitcrepes_spice_sugar = true, saladfurnace = true, trinket_37 = true, ruinshat = true, dragonflychest = true, trinket_36 = true, trinket_35 = true, trinket_33 = true, spear = true, dragon_scales = true, moose = true, oceanfish_small_2 = true, deserthat_blueprint = true, trinket_25 = true, lavaarena_groundlift = true, lavaarena_armor_hppetmastery = true, trinket_18 = true, quagmire_salt = true, trinket_13 = true, backpack_blueprint = true, trinket_9 = true, rabbithole = true, yotc_carrat_gym_direction = true, bananapop_spice_chili = true, trinket_6 = true, blue_mushroom = true, glommerwings = true, trails = true, trinket_3 = true, mushroom_light_blueprint = true, trinket_2 = true, trident = true, quagmire_food_011 = true, homesign = true, coldfirepit_blueprint = true, trinket_32 = true, minotaurchest = true, quagmire_crate_grill = true, molehill = true, barnaclestuffedfishhead_spice_sugar = true, hotchili_spice_chili = true, mast = true,
    succulent_potted_blueprint = true, spore_medium = true, driftwood_small2 = true, bearger = true, toadstool_dark = true, spear_gungnir = true, candybag = true, tentaclespike = true, tentacle_pillar_hole = true, glassspike_med = true, moonglassaxe = true, tent = true, campfire = true, teleportato_crank = true, bedroll_straw_blueprint = true, chesspiece_claywarg_moonglass = true, knight = true, beemine_blueprint = true, tallbirdegg = true, tacklestation = true, jammypreserves = true, bluemooneye = true, oceanfishinglure_spoon_red = true, goose_feather = true, chesspiece_pawn_moonglass = true, moondial_blueprint = true, oceanfishinglure_hermit_drowsy = true, fishingnet = true, oceanfishinglure_hermit_rain_tacklesketch = true, frogglebunwich_spice_chili = true, smallghost = true, oceanfishingbobber_malbatross_tacklesketch = true, oceanfishingbobber_canary_tacklesketch = true, oceanfishingbobber_crow_tacklesketch = true, crabking_claw = true, silk = true, pomegranate_seeds = true, dragonchilisalad_spice_salt = true, ruins_plate = true, table_winters_feast = true, barnacle_cooked = true, sweatervest = true, messagebottle = true, houndstooth = true, bunnyman = true, garlic_cooked = true, sunderarmordebuff = true, mast_malbatross_item_blueprint = true, healingstaff = true, steelwool = true,
    oceanfish_small_9 = true, blowdart_sleep_blueprint = true, staff_tornado_blueprint = true, chesspiece_bishop_stone = true, hermithouse = true, researchlab4_blueprint = true, ruins_statue_mage = true, ruins_statue_head_nogem = true, statuemaxwell = true, potatosouffle_spice_sugar = true, stalagmite_tall_low = true, halloweencandy_3 = true, halloweenpotion_bravery_large = true, quagmire_rubble_pubdoor = true, shadow_rook = true, stalker_fern = true, batwing_cooked = true, spoiled_fish_small = true, stalagmite_tall_full = true, stalagmite_low = true, sapling = true, moonrockcrater_blueprint = true, razor_blueprint = true, trinket_30 = true, fishmeat = true, steeringwheel_item_blueprint = true, chesspiece_hornucopia = true, seafoodgumbo_spice_chili = true, stafflight = true, spidereggsack = true, blowdart_pipe_blueprint = true, dug_grass = true, mermking = true, potatosouffle_spice_chili = true, greenstaff = true, guacamole_spice_sugar = true, gazpacho_spice_garlic = true, lavaarena_groundliftempty = true, winter_food7 = true, ghostlyelixir_fastregen = true, mushroomsprout_dark = true, quagmire_food_027 = true, chesspiece_clayhound_marble = true, humanmeat_dried = true, spiderden_3 = true, book_birds = true, pigtorch = true, saddle_war_blueprint = true, marbletree_3 = true, oceanfishingbobber_ball_floater = true,
    hallowed_nights_event_frontend = true, spider = true, quagmire_rubble_chimney = true, spicepack = true, sandspike = true, powcake_spice_salt = true, quagmire_safe = true, book_gardening = true, frogglebunwich_spice_salt = true, redpouch = true, wetpouch = true, crocommander_rapidfire = true, ruins_table = true, quagmire_wheat = true, mosquito = true, oceanhorror = true, winter_ornament_light8 = true, minimap = true, turf_shellbeach_blueprint = true, slurtlehole = true, quagmire_shadowwaxwell = true, quagmire_park_angel = true, fence_gate_item = true, firesuppressor_blueprint = true, leafloaf_spice_garlic = true, chesspiece_klaus_marble = true, dragonflychest_blueprint = true, horn = true, pinecone_sapling = true, asparagus_cooked = true, slingshotammo_poop = true, shadowtentacle = true, livinglog = true, red_cap = true, cutreeds = true, lightning_rod_blueprint = true, quagmire_food_030 = true, fishsticks_spice_garlic = true, burntfencepost = true, year_of_the_gobbler_event_frontend = true, lavaarena_teambanner = true, oceanfishingbobber_none_floater = true, robin_winter = true, quagmire_food_040 = true, mashedpotatoes_spice_sugar = true, oceanfishinglure_hermit_snow_tacklesketch = true, meatballs_spice_garlic = true, chesspiece_carrat_moonglass = true, beeswax = true, eel = true,
    lost_toy_11 = true, baconeggs_spice_sugar = true, mashedpotatoes_spice_salt = true, orangemooneye = true, eyeturret_item = true, wetgoop_spice_garlic = true, chesspiece_knight_stone = true, garlic_seeds = true, chesspiece_bishop_marble = true, goldnugget = true, gunpowder_blueprint = true, quagmire_food_062 = true, armorskeleton = true, hud = true, bedroll_straw = true, ratatouille_spice_salt = true, heatrock_blueprint = true, telestaff = true, turkeydinner_spice_garlic = true, minisign = true, pavlova = true, twiggytree = true, furtuft = true, oceanfishingbobber_malbatross = true, pondeel = true, potatotornado = true, quagmire_trader_merm2 = true, rottenegg = true, pig_coin = true, quagmire_crate_pot_hanger = true, quagmire_onion_planted = true, statue_marble_muse = true, quagmire_food_055 = true, minifan = true, smallbird = true, quagmire_food_004 = true, leafloaf_spice_chili = true, honeynuggets_spice_chili = true, chesspiece_toadstool = true, peghook = true, bullkelp_plant_leaves = true, oceanfishingbobber_oval_tacklesketch = true, marble = true, houndcorpse = true, lava_pond_rock2 = true, barnaclestuffedfishhead_spice_salt = true, mastupgrade_lamp_item = true, twiggy_nut = true, wetgoop = true, potatotornado_spice_garlic = true,
    signright = true, meat_dried = true, berries_juicy = true, red_mushroomhat_blueprint = true, ruinsrelic_vase_blueprint = true, glommerfuel = true, crabking_claw_shadow = true, portableblender = true, lavaarena_portal = true, moonhound = true, dragonpie_spice_garlic = true, quagmire_grill_item = true, staffcoldlightfx = true, reflectivevest_blueprint = true, lightninggoathorn = true, quagmire_food_plate_burnt = true, dug_berrybush = true, gnarwail_horn = true, trinket_5 = true, brokenwall_hay = true, ceviche_spice_sugar = true, wathgrithr_bloodlustbuff_self = true, lightning_rod = true, quagmire_tomato_planted = true, freshfruitcrepes_spice_salt = true, glassspike = true, stalker_minion2 = true, acorn_sapling = true, pocket_scale_blueprint = true, firestaff_blueprint = true, fencepostright = true, turf_desertdirt = true, moon_altar = true, cave_entrance = true, halloweencandy_4 = true, hawaiianshirt = true, plant_normal_ground = true, deciduoustree_tall = true, icebox = true, ghostlyelixir_retaliation = true, pigelitefighter1 = true, atrium_rubble = true, dragonchilisalad_spice_sugar = true, quagmire_seeds_3 = true, shadow_bishop = true, flowersalad_spice_garlic = true, wortox_eat_soul_fx = true, dragonflyfurnace = true, abigail = true, quagmire_food_060 = true,
    firepit = true, watermelonicle_spice_salt = true, quagmire_altar_ivy = true, stickleft = true, slurtleslime = true, researchlab4 = true, townportaltalisman = true, barnaclepita_spice_chili = true, atrium_key_icon = true, chesspiece_deerclops = true, chesspiece_carrat_sketch = true, yellowgem = true, chesspiece_claywarg_sketch = true, chesspiece_deerclops_sketch = true, quagmire_swampig = true, trails1 = true, gingerbreadhouse = true, shell_cluster = true, seeds_cooked = true, seastack_spawner_swell = true, sculpture_bishop = true, featherhat = true, moonpig = true, ratatouille = true, trinket_10 = true, abigailforcefieldbuffed = true, nightmarepie_spice_salt = true, barbedhelm = true, moon_altar_cosmic = true, ghostflower = true, fertilizer = true, meatrack = true, armor_sanity = true, sapling_moon = true, killerbee = true, sandspike_tall = true, saltlick = true, saltbox = true, saddlehorn = true, moon_altar_rock_seed = true, gazpacho_spice_chili = true, succulent_potted = true, trailmix_spice_salt = true, ruinsrelic_table = true, ruinsrelic_vase = true, researchlab3 = true, chesspiece_butterfly_stone = true, turf_marsh = true, rock_light = true, rock_ice = true,
    gingerbreadpig = true, hound = true, moose_nesting_ground = true, sentryward_blueprint = true, bundlewrap = true, fence_gate_item_blueprint = true, yotc_carrat_gym_reaction = true, sandspike_short = true, voltgoatjelly_spice_chili = true, minisign_blueprint = true, hermithouse_construction1 = true, waxpaper_blueprint = true, barnaclinguine_spice_salt = true, green_mushroom = true, quagmire_salt_rack = true, quagmire_carrot_planted = true, quagmire_oven_item = true, tophat = true, chesspiece_moosegoose_marble = true, flower_evil = true, quagmire_goatmilk = true, quagmire_food_065 = true, quagmire_food_063 = true, oceanfishingbobber_canary = true, quagmire_food_046 = true, beemine_maxwell = true, halloweencandy_1 = true, antlion_sinkhole = true, quagmire_food_012 = true, bananapop_spice_garlic = true, quagmire_seeds_5 = true, wurt_tentacle_warning = true, winter_ornament_fancy3 = true, pighouse = true, quagmire_park_obelisk = true, featherhat_blueprint = true, goldenaxe = true, lost_toy_18 = true, trailmix_spice_garlic = true, leafloaf_spice_salt = true, fishsticks_spice_salt = true, flowersalad_spice_salt = true, fruitmedley_spice_salt = true, spidergland = true, trap_teeth = true, bonestew_spice_sugar = true, mandrakesoup_spice_chili = true, nightmarepie_spice_chili = true, quagmire_food_018 = true, goldenpickaxe = true,
    gazpacho_spice_salt = true, nightmarebeak = true, icecream = true, beebox = true, adventure_portal = true, umbrella_blueprint = true, ghost = true, book_brimstone = true, ruinsrelic_plate_blueprint = true, quagmire_food_002 = true, walkingplank_item = true, buzzard = true, pigelite3 = true, quagmire_mushrooms = true, chesspiece_hornucopia_moonglass = true, crabking = true, chesspiece_crabking_marble = true, mutated_penguin = true, chester_eyebone = true, oceanfishingbobber_malbatross_floater = true, perdshrine_blueprint = true, feather_canary = true, spider_warrior = true, saddlehorn_blueprint = true, chesspiece_butterfly_moonglass = true, van_knight = true, evergreen_normal = true, burntstickright = true, researchlab = true, skeletonhat = true, seafoodgumbo = true, pepperpopper_spice_chili = true, berrybush_juicy = true, cane = true, acorn_cooked = true, year_of_the_gobbler_event_global = true,
}
local fx_prefabs = {
    [1] = {sporecloud = true, gargoyle_werepighowl_fx = true, blossom_hit_fx = true, weregoose_feathers3 = true, wave_shimmer = true, redpouch_unwrap = true, sleepcloud = true, pine_needles_chop = true, slow_steam_fx5 = true, coconut_chunks = true, slingshotammo_hitfx_thulecite = true, cavein_dust_low = true, groundpound_fx = true, spellmasteryorb = true, lavaarena_spawnerdecor_fx_3 = true, propsignshatterfx = true, toadstool_cap_absorbfx = true, wave_shimmer_med = true, shadow_shield1 = true, lavaarena_firebomb_explosion = true, weaponsparks_bounce = true, weregoose_transform_fx = true, reticuleaoeping = true, goosplash5 = true, stalker_shield4 = true, toadstool_cap_releasefx = true, singingshell_creature_woodfx = true, eyeflame = true, fossilized_break_fx = true, crater_steam_fx4 = true, lantern_tesla_fx_held = true, sinkhole_spawn_fx_1 = true, splash_green = true, quagmire_tomato_leaf = true, float_fx_back = true, goosplash7 = true, peghook_splashfx = true, ghostlyelixir_fastregen_dripfx = true, icebox_victorian_frost_fx = true, hermit_bundle_unwrap = true, waterballoon_splash = true, ground_trail = true, sinkhole_warn_fx_3 = true, abigailsummonfx = true, yellow_leaves = true, spat_splat_fx = true, werebeaver_transform_fx = true, sounddebugicon = true, electricchargedfx = true, weregoose_splash_med2 = true
    },
    [2] = {crab_king_bubble2 = true, mining_fx = true, sand_puff = true, diseaseflies = true, moose_nest_fx_idle = true, snow = true, explode_firecrackers = true, statue_transition_2 = true, icing_splash_fx_melted = true, bramblefx_trap = true, slingshotammo_hitfx_freeze = true, winters_feast_depletefood = true, lavaarena_firebomb_sparks = true, halloween_firepuff_cold_1 = true, firebomb_explosion = true, lavaarena_spawnerdecor_fx_2 = true, splash_ocean = true, slingshotammo_hitfx_rocks = true, ink_splash = true, fire = true, icespike_fx_2 = true, miniboatlantern_loseballoon = true, fossilizing_fx_2 = true, lavaarena_fossilizedebris = true, weaponsparks_thrusting = true, cointosscastfx = true, reticuleline2 = true, mushtree_tall_burntfx = true, tears = true, cavein_debris = true, wave_shimmer_deep = true, wetpouch_unwrap = true, bee_poof_big = true, boat_malbatross_mast_sink_fx = true, mossling_spin_fx = true, firesuppressor_glow = true, deer_ice_fx = true, cavelight_atrium = true, superjump_debris = true, fireball_hit_fx = true, mushtree_medium_burntfx = true, fossilizing_fx_1 = true, lavaarena_bloom = true, ocean_splash_med2 = true, oceanfishinghook_ripple = true, quagmire_coin_fx = true, waterstreak_burst = true, forginghammer_cracklebase_fx = true, sinkhole_spawn_fx_2 = true, reticuleaoesummonping = true
    },
    [3] = {petrified_tree_fx_tall = true, shovel_dirt = true, spellmasterybuff = true, lavaarena_groundtargetblocker = true, reticuleaoecctarget = true, reticuleaoesmallhostiletarget = true, weregoose_splash_med1 = true, gargoyle_werepigatk_fx = true, cointosscastfx_mount = true, quagmire_salting_bowl_fx = true, fossilizing_fx = true, lavaarena_creature_teleport_smoke_fx_1 = true, mining_ice_fx = true, weregoose_splash_less2 = true, rhinodrill_fossilized_break_fx_right = true, squid_ink_player_fx = true, icespike_fx_1 = true, shadow_shield5 = true, lavaarena_spawnerdecor_fx_1 = true, reticuleaoefriendlytarget = true, staffcastfx_mount = true, halloween_firepuff_cold_3 = true, splash_green_small = true, weremoose_revert_fx = true, abigail_retaliation = true, goo_spit_fx = true, shadow_shield2 = true, deer_ice_charge = true, honey_splash = true, wood_splinter_jump = true, lavaarena_meteor_splashhit = true, waterplant_pollen_fx = true, shadow_bishop_fx = true, winona_battery_high_shatterfx = true, peghook_hitfx = true, quagmire_park_gate_anim = true, plant_dug_small_fx = true, lavaarena_creature_teleport_smoke_fx_2 = true, vomitfire_fx = true, sanity_lower = true, lantern_tesla_fx_ground = true, explode_small = true, quagmire_turnip_leaf = true, shadowhand_fx = true, quagmire_seedpacket_unwrap = true, coldfirefire = true, shadow_shield3 = true, lavaarena_bloom1 = true, sporecloud_overlay = true, hammer_mjolnir_cracklebase = true
    },
    [4] = {mastupgrade_lightningrod_fx = true, torchfire_carrat = true, waterplant_pollen_fx_ocean = true, statue_transition = true, wintersfeastbuff_fx = true, quagmire_wheat_leaf = true, sleepbomb_burst = true, ocean_splash_small2 = true, sinkhole_warn_fx_1 = true, multiplayer_portal_moonrock_fx = true, lavaarena_bloom4 = true, mushtree_tall_webbed_burntfx = true, goosplash8 = true, spawn_fx_small = true, ghostlyelixir_slowregen_fx = true, washashore_puddle_fx = true, shadow_shield6 = true, lavaarena_meteor = true, meteorwarning = true, merm_king_splash = true, boat_water_fx = true, ghostlyelixir_fastregen_fx = true, lavae_move_fx = true, dr_warm_loop_1 = true, lavaarena_meteor_splash = true, mushtree_tall_bloom_burntfx = true, firebomb_proc_fx = true, lightning_rod_fx = true, attune_ghost_in_fx = true, messagebottle_bob_fx = true, gargoyle_houndatk_fx = true, wave_splash = true, ocean_splash_small1 = true, purple_leaves_chop = true, lavaarena_fossilizedebris2 = true, werebeaver_shock_fx = true, shadowstrike_slash_fx = true, groundpoundring_fx = true, forge_fireball_hit_fx = true, abigailunsummonfx = true, tauntfire_fx = true, reviver_cupid_beat_fx = true, singingshell_creature_rockfx = true, spawn_fx_small_high = true, redpouch_yotp_unwrap = true, slingshotammo_hitfx_marble = true, lavaarena_player_revive_from_corpse_fx = true, disease_puff = true, orange_leaves = true, halloween_firepuff_3 = true
    },
    [5] = {book_fx_mount = true, lavaarena_creature_teleport_medium_fx = true, goosplash6 = true, shadowwatcher = true, bramblefx_armor = true, thurible_smoke = true, reticulelongmultiping = true, weregoose_splash = true, torchfire_spooky = true, lavaarena_fossilizedebris1 = true, green_leaves = true, reticuleaoesmall = true, abigaillevelupfx = true, splash = true, nightlight_flame = true, positronbeam_front = true, reticuleaoehostiletarget = true, gargoyle_hounddeath_fx = true, abigail_vex_hit = true, lucy_ground_transform_fx = true, ghost_transform_overlay_fx = true, reticule = true, firehit = true, infernalstaff_meteor_splash = true, deer_growantler_fx = true, red_leaves = true, townportalsandcoffin_fx = true, spat_splash_fx_low = true, reticulelongmulti = true, crater_steam_fx1 = true, attackfire_fx = true, infernalstaff_meteor_splashbase = true, quagmire_grill_small = true, lavaarena_creature_teleport_small_fx = true, lavaarena_firebomb_proc_fx = true, impact = true, sugarwood_leaf_withered_fx = true, fence_gate_anim = true, dr_warm_loop_2 = true, quagmire_potato_leaf = true, crab_king_shine = true, firering_fx = true, warningshadow = true, stalker_shield3 = true, bee_poof_small = true, gestalt_trail = true, positronbeam_back = true, ice_splash = true, crab_king_bubble3 = true, crabking_chip_low = true
    },
    [6] = {lavaarena_bloom2 = true, blossom_cast_fx = true, infernalstaff_meteor = true, splash_spiderweb = true, oceanhorror_ripples = true, sparks = true, mole_move_fx = true, ink_puddle_water = true, icespike_fx_4 = true, wave_shimmer_flood = true, lighterfire_haunteddoll = true, tree_petal_fx_chop = true, slingshotammo_hitfx_trinket_1 = true, hammer_mjolnir_cracklehit = true, nightsword_curve_fx = true, redpouch_yotc_unwrap = true, cane_ancient_fx = true, reticuleaoe = true, wave_shore = true, crab_king_icefx = true, lavaarena_bloom6 = true, lantern_winter_fx_ground = true, gestalt_head = true, circlingbuzzard = true, icebox_coffin_bat_fx = true, yotc_seedpacket_rare_unwrap = true, amplify_fx = true, weremoose_transform2_fx = true, reticulelongping = true, battlecry_fx_other = true, cavein_dust_high = true, splash_snow_fx = true, poison_trail = true, slingshotammo_hitfx_slow = true, crabking_chip_high = true, deerclops_laserscorch = true, quagmire_crate_unwrap = true, shadow_puff = true, crater_steam_fx2 = true, cavelight_tiny = true, reticulelineping = true, singingshell_critterfx = true, spawn_fx_medium = true, weaponsparks_piercing = true, dr_hot_loop = true, frostbreath = true, lavaarena_creature_teleport_smoke_fx_3 = true, forge_electrocute_fx = true, nightsword_sharp_fx = true, explode_small_slurtlehole = true
    },
    [7] = {round_puff_fx_hi = true, cane_ancient_fx1 = true, halloween_moonpuff = true, icespike_fx_3 = true, wake_small = true, burnt_marsh_bush_erode = true, slow_steam_fx3 = true, stalker_shield = true, boat_mast_sink_fx = true, ink_puddle_land = true, deer_ice_circle = true, slow_steam_fx1 = true, messagebottle_break_fx = true, mushtree_small_burntfx = true, staffcastfx = true, abigail_vex_debuff = true, mushtree_medium_bloom_burntfx = true, lavaarena_bloom5 = true, explode_small_slurtle = true, batbat_bats = true, halloween_firepuff_2 = true, stalker_shield1 = true, crab_king_bubble1 = true, shock_fx = true, mushroomsprout_glow = true, cavelight = true, plant_dug_large_fx = true, slingshotammo_hitfx_poop = true, spawn_fx_tiny = true, flies = true, rhinobumpfx = true, spat_splash_fx_full = true, weregoose_splash_less1 = true, cane_sharp_fx = true, deer_ice_flakes = true, shadow_puff_large_front = true, pigtorch_flame = true, ghostlyelixir_shield_fx = true, crab_king_waterspout = true, ghostflower_spirit2_fx = true, beefalo_transform_fx = true, wave_med = true, wathgrithr_spirit = true, gooball_hit_fx = true, ocean_splash_ripple1 = true, weregoose_shock_fx = true, battlecry_fx_self = true, firepit_firebird_puff_fx = true, shatter = true, quagmire_salting_plate_fx = true
    },
    [8] = {shadow_despawn = true, abigailunsummonfx_mount = true, scorchedground = true, quagmire_cooking_buff = true, forge_reticule = true, weaponsparks_thrusting_fx = true, weaponsparks_piercing_fx = true, weaponsparks_fx = true, forgedebuff_fx = true, forgespear_fx = true, forginghammer_crackle_fx = true, deer_fire_charge = true, pollen_cloud_fx = true, bloom_fx = true, debuff_spice = true, debuff_fire = true, fan_wheel = true, infernalstaff_meteor_splashhit = true, float_fx_front = true, goosplash3 = true, lucyspin_fx = true, explosivehit = true, grasspartfx = true, spat_splash_fx_melted = true, icing_splash_fx_low = true, fireball_cast_fx = true, hermit_bundle_shells_unwrap = true, merm_splash = true, slide_puff = true, slow_steam_fx4 = true, tumbleweedbreakfx = true, icebox_crystal_fx = true, moose_nest_fx_hit = true, shadowhand_arm = true, slow_steam_fx2 = true, orange_leaves_chop = true, goosplash1 = true, round_puff_fx_sm = true, firebomb_sparks = true, ghostlyelixir_slowregen_dripfx = true, shadow_teleport_out = true, icing_splash_fx_full = true, goosplash2 = true, slurper_respawn = true, electrichitsparks = true, sinkhole_warn_fx_2 = true, wortox_soul_in_fx = true, wortox_soul_heal_fx = true, character_fire = true, spice_explosion = true
    },
    [9] = {petrified_tree_fx_short = true, torchfire_rag = true, petrified_tree_fx_old = true, weregoose_feathers1 = true, cane_ancient_fx3 = true, reticulearcping = true, ghostlyelixir_retaliation_dripfx = true, sanity_raise = true, rhinodrill_fossilized_break_fx = true, forge_gooball_hit_fx = true, erode_ash = true, weregoose_ripple1 = true, rhinodrill_fossilized_break_fx_left = true, fx_boat_crackle = true, ghostlyelixir_attack_fx = true, ocean_splash_med1 = true, cracklehitfx = true, poopcloud = true, maxwell_smoke = true, green_leaves_chop = true, forge_blossom_hit_fx = true, sand_puff_large_front = true, campfirefire = true, ghostlyelixir_speed_fx = true, gift_unwrap = true, deer_ice_burst = true, lucy_transform_fx = true, slingshotammo_hitfx_gold = true, ocean_splash_ripple2 = true, ember_short_fx = true, deer_fire_flakes = true, winona_battery_sparks = true, raindrop = true, weaponsparks = true, burntground_faded = true, lantern_winter_fx_held = true, plant_dug_medium_fx = true, quagmire_portal_player_fx = true, collapse_big = true, lavaarena_spawnerdecor_fx_small = true, ghostlyelixir_retaliation_fx = true, icebox_porcelain_fx = true, sinkhole_spawn_fx_3 = true, gargoyle_werepigdeath_fx = true, cane_candy_fx = true, torchfire_shadow = true, shadow_teleport_in = true, fossilspike2_base = true, bundle_unwrap = true, shadow_shield4 = true
    },
    [10] = {battreefx = true, malbatross_ripple = true, reticuleaoesummontarget = true, wood_splinter_drill = true, reticuleline = true, lighterfire = true, spat_splash_fx_med = true, purple_leaves = true, lantern_crystal_fx_held = true, creepyeyes = true, mining_moonglass_fx = true, lantern_crystal_fx_ground = true, reticuleaoesummon = true, weregoose_ripple2 = true, burntground = true, ghostlyelixir_shield_dripfx = true, wormwood_plant_fx = true, torchfire = true, deerclops_lasertrail = true, quagmire_garlic_leaf = true, quagmire_oven = true, petrified_tree_fx_normal = true, sugarwood_leaf_withered_fx_chop = true, superjump_fx = true, glass_fx = true, goosplash4 = true, shadowskittish = true, collapse_small = true, weaponsparks_bouncing_fx = true, splash_sink = true, stalker_shield2 = true, quagmire_portal_playerdrip_fx = true, quagmire_grill = true, yotc_seedpacket_unwrap = true, deer_fire_circle = true, round_puff_fx_lg = true, reticuleaoesmallping = true, deer_fire_burst = true, icing_splash_fx_med = true, sugarwood_leaf_fx = true, icing_splat_fx = true, weregoose_feathers2 = true, abigailsummonfx_mount = true, cane_ancient_fx2 = true, spear_gungnir_lungefx = true, peghook_spitfx = true, petrified_trunk_break_fx = true, halloween_firepuff_cold_2 = true, flotsam_puddle = true, smoke_plant = true
    },
    [11] = {goosplash = true, crater_steam_fx3 = true, waterplant_destroy = true, sleepcloud_overlay = true, atrium_light_back = true, hutch_music_light_fx = true, quagmire_pot_hanger = true, ghostlyelixir_speed_dripfx = true, ice_puddle = true, red_leaves_chop = true, firesplash_fx = true, explode_reskin = true, shadowstrike_slash2_fx = true, waxwell_book_fx = true, sand_puff_large_back = true, sporebomb = true, halloween_firepuff_1 = true, lavaarena_fossilizedebris3 = true, die_fx = true, crabking_ring_fx = true, damp_trail = true, small_puff = true, pandorachest_reset = true, quagmire_portal_player_splash_fx = true, attune_in_fx = true, fx_boat_pop = true, ghostlyelixir_attack_dripfx = true, mushtree_small_bloom_burntfx = true, emote_fx = true, lavaarena_bloom3 = true, shadow_puff_large_back = true, positronpulse = true, chester_transform_fx = true, sugarwood_leaf_fx_chop = true, splash_green_large = true, honey_trail = true, lavaarena_meteor_splashbase = true, mudpuddle_splash = true, book_fx = true, ghostflower_spirit1_fx = true, lavaarena_portal_player_fx = true, attune_out_fx = true, ground_chunks_breaking = true, lavaarena_lucy_spin = true, weremoose_transform_fx = true, fishingnetvisualizerfx = true, reticulelong = true, cane_victorian_fx = true, atrium_gate_activatedfx = true, quagmire_onion_leaf = true
    },
    [12] = {quagmire_carrot_leaf = true, quagmire_oven_back = true, pollen = true, waterplant_burr_burst = true, crabking_chip_med = true, yellow_leaves_chop = true, chesterlight = true, fossilspike_base = true, weremoose_shock_fx = true, dr_warmer_loop = true, merm_spawn_fx = true, frogsplash = true, flotsam_break = true, cavelight_small = true, winters_feast_food_depleted = true, deer_unshackle_fx = true, hutch_move_fx = true, hammer_mjolnir_crackle = true, reticulearc = true, battlesong_sanitygain_fx = true, bile_puddle_water = true, dirt_puff = true, bile_puddle_land = true, battlesong_instant_panic_fx = true, spider_heal_ground_fx = true, alterguardian_phase3trapprojectile = true, farm_plant_happy = true, balloon_pop_body = true, spider_heal_target_fx = true, spider_heal_fx = true, moon_altar_crown_break = true, carnival_confetti_fx = true, alterguardian_summon_fx = true, cavelightmoon_tiny = true, cavelightmoon = true, oceantree_pillar_leaves = true, spider_mutate_fx = true, archive_lockbox_player_fx = true, battlesong_fireresistance_fx = true, carnival_seedpacket_unwrap = true, balloonparty_confetti_cloud = true, moonstorm_lightning = true, battlesong_instant_electric_fx = true, cavelightmoon_small = true, mushtree_moon_burntfx = true, farm_plant_unhappy = true,
        --moonstorm_ground_lightning_fx = true,
        battlesong_detach = true, balloonparty_confetti_balloon = true, gestalt_guard_head = true,
    },--lightning = true,
    [13] = { moon_altar_claw_break = true, oceantree_pillar_ripples = true, carnival_streamer_fx = true, confetti_fx = true, carnival_sparkle_fx = true, oceantree_leaf_fx_fall = true, moonstorm_glass_ground_fx = true, alterguardian_spike_breakfx = true, moonpulse_fx = true, moonpulse2_fx = true, carnival_unwrap_fx = true, oceantree_leaf_fx_chop = true, moon_geyser_explode = true, moon_altar_link_contained = true, battlesong_attach = true, moon_altar_link_fx = true, alterguardian_spintrail_fx = true, debuff_mfd = true, gauntlet_tail_fx = true, gauntlet_ground_fx = true, yotb_post_spotlight = true, battlesong_healthgain_fx = true, watertree_pillar_ripples = true, bilesplat = true, battlesong_instant_taunt_fx = true, watertree_pillar_roots = true, alterguardian_laserscorch = true, treegrowthsolution_use_fx = true, chandelier_fire = true, battlesong_loop = true, battlesong_sanityaura_fx = true, cane_harlequin_fx = true, alterguardian_phase1fallfx = true, alterguardian_phase3trappst = true, bile_splash = true, yotb_confetti = true, moon_device_break_stage2 = true, oceantree_pillar_roots = true, moonstorm_glass_fx = true, spore_moon_coughout = true, lantern_flower_fx_ground = true, archive_resonator_base = true, moon_device_break_stage3 = true, archive_chandelier = true, moon_device_break_stage1 = true, moon_altar_break = true, chandelier_sfx = true, moonstorm_spark_shock_fx = true, lantern_flower_fx_held = true, alterguardian_lasertrail = true
    },
    [14] = {balloon_pop_head = true, battlesong_durability_fx = true, redpouch_yotb_unwrap = true, lightning = true
    },
}
local projectile_prefabs = {
    [1] = {messagebottle_throwable = true, oceanfishingbobber_oval_projectile = true, forge_fireball_projectile_fast = true, slingshotammo_poop_proj = true, blowdart_yellow = true, spice_buff_bomb_dmg_projectile = true, blowdart_lava2_projectile = true, slingshotammo_slow_proj = true, firebomb_projectile = true, blowdart_lava_projectile_alt = true, ice_projectile = true, mushroombomb_dark_projectile = true, oceanfishingbobber_ball_projectile = true, seed_projectile = true, waterballoon = true, eye_charge = true, forge_fireball_projectile = true, snowball = true, spice_buff_bomb_regen_projectile = true, slingshotammo_marble_proj = true, oceanfishingbobber_canary_projectile = true, waterplant_projectile = true, oceanfishingbobber_robin_winter_projectile = true, oceanfishingbobber_plug_projectile = true, oceanfishingbobber_malbatross_projectile = true, food_projectile = true, slingshotammo_gold_proj = true, oceanfishingbobber_goose_projectile = true, forge_slingshot_projectile = true, riledlucy = true, spider_web_spit = true, slingshotammo_rock_proj = true, forge_fireball_projectile_big = true, fire_projectile = true, waterplant_bomb = true, spice_bomb_projectile = true, boomerang = true, blowdart_pipe = true, blowdart_sleep = true, monkeyprojectile = true, wortox_soul_spawn = true, sleepbomb = true, forgedarts_projectile_alt = true, mushroombomb_projectile = true, forgedarts_projectile = true, blossom_projectile = true, spice_buff_bomb_speed_projectile = true, fireball_projectile = true, acid_breath_projectile = true, coconut = true,
    },
    [2] = {forge_gooball_projectile = true, waterstreak_projectile = true, spice_buff_bomb_def_projectile = true, slingshotammo_thulecite_proj = true, snaptooth_seed_projectile = true, oceanfishingbobber_crow_projectile = true, forge_blossom_projectile = true, bishop_charge = true, oceanfishingbobber_none_projectile = true, blowdart_lava_projectile = true, moltendarts_projectile = true, forge_slingshot_projectile_alt = true, gooball_projectile = true, trinket_1_proj = true, winona_catapult_projectile = true, moltendarts_projectile_explosive = true, blowdart_fire = true, peghook_projectile = true, slingshotammo_freeze_proj = true, spat_bomb = true, lavaarena_firebomb_projectile = true, oceanfishingbobber_robin_projectile = true, inksplat = true, blowdart_walrus = true, blowdart_lava2_projectile_explosive = true, oceanfishingbobber_twig_projectile = true, gestalt_alterguardian_projectile = true, largeguard_alterguardian_projectile = true, alterguardianhat_projectile = true, smallguard_alterguardian_projectile = true,
    },
}
local function IsKnownPrefab(name, tab)
    for _,prefabs in pairs(tab) do
        if prefabs[name] then
            return true
        end
    end
    return false
end
AddPrefabPostInit("world", function(self)
    self:ListenForEvent("ms_forge_allplayersspawned", function()
        local ignore_prefabs = {rain = true, lavaarena = true, quagmire = true, gestalt = true, world = true, forest_network = true, caverain = true, mist = true, cave_network = true, cave = true, forest = true,
            chum_aoe = true, hf_eye_arena = true, hf_eye_arena_network = true, }
        self.fx_prefabs = {}
        self.projectile_prefabs = {}
        self.other_prefabs = {}
        local function CreateFX(name, pos, force_remove)
            local pref = _G.SpawnPrefab(name)
            if pref == nil then return false end
            if (pref:HasTag("projectile") or pref:HasTag("FX")) and pref.Transform then
                if true or not force_remove then
                    pref.Transform:SetPosition(pos:Get())
                    pref:ListenForEvent("onremove", function(inst)
                        CreateFX(name, pos)
                    end)
                    table.insert(pref:HasTag("projectile") and self.projectiles_prefabs or self.fx_prefabs, name)
                else
                    pref:Remove()
                end
                return true
            else
                table.insert(self.other_prefabs, name)
                pref:DoTaskInTime(10*_G.FRAMES, pref.Remove)
                return false
            end
        end
        local function PrintPrefabs(prefabs)
            local str = ""
            for i,name in pairs(prefabs) do
                str = str .. ", " .. name .. " = true"
                if i%50 == 0 then
                    print(str)
                    str = ""
                end
            end
            print(str)
        end
        -- Organize prefabs by type and print them
        self.GetValidPrefabs = function(self, ignore_known_prefabs)
            local index = 1
            local count = 1
            local inc = 50
            local min = 0
            local max = 100
            for _,data in pairs(_G.Prefabs) do
                Debug:Print("Prefab Index " .. tostring(index) .. ": ", "log")
                index = index + 1
                if count > (max*inc) then break end
                if data.name and data.fn and data.assets and #data.assets > 0 and not ignore_prefabs[data.name] and not other_prefabs[data.name] then
                    Debug:Print("Attempting to spawn " .. tostring(data.name) .. "...", "log")
                    if ignore_known_prefabs or not (IsKnownPrefab(data.name, fx_prefabs) or IsKnownPrefab(data.name, projectile_prefabs) or other_prefabs[data.name]) then
                        local pos = Point(count%10*4, 0, math.floor(count/10)*4)
                        local success = CreateFX(data.name,pos,count>(min*inc))
                        if success then
                            print("- successfully spawned at position: " .. tostring(pos))
                            count = count + 1
                        end
                    else
                        print("- known prefab")
                    end
                end
            end
            print("Other Prefabs:")
            PrintPrefabs(self.other_prefabs)
            print("FX Prefabs:")
            PrintPrefabs(self.fx_prefabs)
            print("Projectile Prefabs:")
            PrintPrefabs(self.projectile_prefabs)
        end

        local prefab_index_link = {}
        self.fx_list = {}
        self.max_fx = 50
        self.fx_origin = _G.Point(0,0,0)
        local function GetFXList(type)
            return type == "projectile" and projectile_prefabs or type == "fx" and fx_prefabs or fx_prefabs
        end
        local function CreateFXTest(index, set, pos, prev_prefab_set)
            if not self.fx_display_on then return end
            local index_link = index + (self.prefab_set - 1)*self.max_fx
            local index_set = prefab_index_link[math.ceil(index_link / 50)]
            local name = index_set and index_set[index_link%50]
            if name then
                if prev_prefab_set ~= self.prefab_set then
                    Debug:Print("Spawning " .. tostring(name) .. "(" .. tostring(index) .. ") at position: " .. tostring(pos), "log")
                end
                local pref = _G.SpawnPrefab(name)--_G.c_spawn(name)
                if pref then
                    pref.Transform:SetPosition((self.fx_origin + pos):Get())
                    pref.prefab_set = self.prefab_set
                    pref:ListenForEvent("onremove", function(inst)
                        if self.prefab_set == pref.prefab_set then
                            CreateFXTest(index, set, pos, pref.prefab_set)
                            _G.RemoveTask(pref.anim_task)
                        end
                    end)
                    self.fx_list[index] = pref

                    if self.type == "projectile" then
                        pref.anim_task = pref:DoTaskInTime(1.5, function(inst)
                            if pref.AnimState and pref.AnimState:GetCurrentAnimationLength() < pref.AnimState:GetCurrentAnimationTime() then
                                pref:Remove()
                            end
                        end)
                    end
                else
                    Debug:Print("FX Display failed to spawn " .. tostring(name), "error")
                end
            else
                self.fx_list[index] = nil
                local prev_prefab_set = self.prefab_set
                self:DoTaskInTime(10, function(inst)
                    CreateFXTest(index, set, pos, prev_prefab_set)
                end)
            end
        end
        self.SetFXDisplayOrigin = function(self, origin)
            self.fx_origin = origin or _G.ThePlayer and _G.ThePlayer:GetPosition() or self.fx_origin
        end
        self.dist = 4
        self.fx_per_row = 10
        self.CreateFXDisplay = function(self, dist, fx_per_row, origin, max, starting_set)
            if not self.fx_display_on then
                self.fx_display_on = true
                self.max_fx = max or self.max_fx
                self.dist = dist or 4
                self.fx_per_row = fx_per_row or 10
                self:SetFXDisplayOrigin(origin)
                local count = 0
                for set,data in pairs(GetFXList(self.type)) do
                    if not starting_set or set >= starting_set then
                        for name,_ in pairs(data) do
                            if count >= self.max_fx then break end
                            count = count + 1
                            local pos = Point(count%self.fx_per_row*self.dist, 0, math.floor(count/self.fx_per_row)*self.dist)
                            CreateFXTest(count,set,pos)
                        end
                    end
                end
            end
        end

        self.RemoveAllFX = function(self, reset_display)
            for _,fx in pairs(self.fx_list or {}) do
                fx:Remove()
            end
            self.fx_list = {}
        end
        self.RemoveFXDisplay = function(self)
            self.fx_display_on = false
            self:RemoveAllFX()
        end

        self.ChangeFXType = function(self, type)
            local type = type or "fx"
            if not self.type or self.type ~= type then
                self.type = type
                -- Update Fx index link
                prefab_index_link = {}
                for set,data in pairs(GetFXList(type) or {}) do
                    for name,_ in pairs(data or {}) do
                        if not prefab_index_link[set] then prefab_index_link[set] = {} end
                        table.insert(prefab_index_link[set], name)
                    end
                end
                self:RemoveAllFX()
            end
        end
        self.prefab_set = 1
        self:ChangeFXType()
        self.ChangeFXSet = function(self, val)
            if not self.prefab_set or self.prefab_set ~= val then
                Debug:Print("Changing FX set from " .. tostring(self.prefab_set) .. " to " .. tostring(val), "log")
                self.prefab_set = val or self.prefab_set
                self:RemoveFXDisplay()
                self:CreateFXDisplay(self.dist, self.fx_per_row, self.fx_origin, self.max_fx, self.prefab_set)
            end
        end
    end)
end)
